[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = "AfrDEAwXxkRy2t8Xckoi3CHnawRSEXBEQwxoTW9Rhigy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/desy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
